### PR TITLE
Make the code compatible with conll-2012 directory structure

### PR DESCRIPTION
**Pull request by ghaddarAbs**
Make the preprocessing of ontonotes compatible with the directory structure produced by skeleton2conll.sh script of conll-2012 shared task

### CODE REVIEW

**Comment by kamalkraj** [comment]
fails to pre-process data from test folder. I think it is because the v9 test doesn't contain /*/*_gold_conll files

**Comment by ghaddarAbs** [comment]
You must use the v4 train/dev/test split. Here are the stats:

num train examples: 59924
num train tokens: 1088503

num dev examples: 8262
num dev tokens: 152728

**Comment by kamalkraj** [comment]
V4 test split is not available in the website , can you share here

**Comment by ghaddarAbs** [comment]
Unfortunately i can't.... the dataset is copyrighted!!!
However you can download ontonotes from [ldc](https://catalog.ldc.upenn.edu/ldc2013t19) (its free!!!)
Then you have to follow the instructions of the [conll-2012 shared task data preprocessing](http://conll.cemantix.org/2012/data.html)

**Comment by kamalkraj** [comment]
I have access to ontonotes 5.0 
In the website [conll-2012 shared task data preprocessing](http://conll.cemantix.org/2012/data.html)
only test v9 is avialble
test

**Comment by ghaddarAbs** [comment]
What is you are looking for is The [Test Key](http://conll.cemantix.org/2012/download/test/conll-2012-test-key.tar.gz) directly below Test Data

**Comment by kamalkraj** [comment]
got it

**Comment by ghaddarAbs** [comment]
The [scripts](http://conll.cemantix.org/2012/download/conll-2012-scripts.v3.tar.gz) are in the [same page](http://conll.cemantix.org/2012/data.html)

**Comment by strubell** [comment]
Thanks!

**Pull request merged**
